docs/development.md, manifests/examples/dev/cluster-defaults.yaml, manifests/examples/dev/minimal-setup.yaml, manifests/examples/openshift/base/minimal-setup.yaml, manifests/generate-manifests.ps1, manifests/install/all/base/rbac/cluster-role.yaml, manifests/install/dev/kustomization.yaml, manifests/install/dev/overlays/deployment.yaml, manifests/install/examples/classicfullstack-chaining/README.md, manifests/install/examples/classicfullstack-chaining/kustomization.yaml, src/Contrast.K8s.AgentOperator/Controllers/DynaKubeController.cs, src/Contrast.K8s.AgentOperator/Core/Chaining/DynaKubeHandler.cs, src/Contrast.K8s.AgentOperator/Core/Reactions/Injecting/Patching/Agents/DotNetPatcher.cs, src/Contrast.K8s.AgentOperator/Entities/Dynatrace/V1Beta1DynaKube.cs, src/Contrast.K8s.AgentOperator/Options/InjectorOptions.cs, src/Contrast.K8s.AgentOperator/Program.cs, src/Contrast.K8s.AgentOperator/Properties/launchSettings.json, src/Contrast.K8s.AgentOperator/Startup.cs, tests/Contrast.K8s.AgentOperator.Tests/Core/Reactions/Injecting/Patching/Agents/DotNetPatcherTests.cs
Adds support for detecting dynatrace's classicFullStack mode and instructs the user to set CONTRAST_ENABLE_EARLY_CHAINING on the operator.
This will cause LD_PRELOAD for our ContrastChainLoader to be set during the initial pod patching. This will cause dynatrace in cloudNativeFullStack or applicationMonitoring mode to no longer chain so this is an opt-in setting.
This PR also updates the docs for local development and adds an example of setting CONTRAST_ENABLE_EARLY_CHAINING
=> DOTNET-4426 Early preload chaining support

manifests/examples/testing/scenarios/namespaced/injection-java-tooloptions.yaml, manifests/examples/testing/scenarios/namespaced/injection-javatooloptions.yaml, manifests/examples/testing/scenarios/namespaced/kustomization.yaml, src/Contrast.K8s.AgentOperator/Core/Reactions/Injecting/Patching/Agents/JavaAgentPatcher.cs, src/Contrast.K8s.AgentOperator/Core/Reactions/Injecting/Patching/Utility/JavaArgumentParser.cs, src/Contrast.K8s.AgentOperator/Core/Telemetry/Services/Exceptions/TelemetryExceptionsTarget.cs, tests/Contrast.K8s.AgentOperator.FunctionalTests/Scenarios/Injection/Agents/JavaToolOptionsInjectionTests.cs, tests/Contrast.K8s.AgentOperator.Tests/Core/Reactions/Injecting/Patching/Agents/JavaAgentPatcherTests.cs, tests/Contrast.K8s.AgentOperator.Tests/Core/Reactions/Injecting/Patching/Utility/JavaArgumentParserTests.cs
If a pod already has JAVA_TOOL_OPTIONS set on it, this new logic will parse and patch in our `-javaagent:contrast-agent.jar` argument. This also handles if `contrast-agent.jar` is already present and sets it to the correct path.
=> DOTNET-4544 Add support for patching existing JAVA_TOOL_OPTIONS

.github/workflows/pipeline.yml
This fixes the issue of PR builds failing due to not having write permissions to the repo.
The image push and k3s image test step can be manually triggered by workflow_dispatch.
=> Build but don't push the docker image for PR builds

manifests/helm/build/templates/overlays/deployment.yaml, manifests/helm/templates/image-pull-secrets.yaml.tpl, manifests/helm/values.yaml
Allow configuration of a named secret which will be included in the `imagePullSecrets` spec for the operator image.
Configuration allows for the optional creation of the `dockerconfigjson` secret with provided credentials.
Have tested with:
1. No named secret defined - works for public repo, fails as expected for private `ghcr.io` repository
2. `imageCredentials.enabled=true` and a set of credentials to pull an image from private `ghcr.io` repository
3. `imageCredentials.enabled=false` and a manually created secret in the `contrast-agent-operator` namespace to pull an image from private `ghcr.io` repository
=> Allow imagePullSecrets to be added via Helm.

src/Contrast.K8s.AgentOperator/Core/Reactions/Injecting/Patching/Agents/IAgentPatcher.cs, src/Contrast.K8s.AgentOperator/Core/Reactions/Injecting/Patching/Agents/NodeJsProtectAgentPatcher.cs, src/Contrast.K8s.AgentOperator/Core/Reactions/Injecting/Patching/PodPatcher.cs, src/Contrast.K8s.AgentOperator/Entities/V1Beta1AgentInjector.cs
With the release of the nodejs v5 agent, the nodejs-protect agent is being deprecated.
This adds support for deprecating an agent patcher and logging a warning if it is used.
=> DOTNET-5476 Deprecate nodejs-protect agent injector

manifests/helm/templates/agent-injectors.yaml.tpl, manifests/helm/values.testing.yaml, manifests/helm/values.yaml
Adding support for the chart to create `AgentInjectors`.
As it is common for a cluster to contain several namespaces, and multiple languages are supported by the operator, this takes in an array of injectors, where each injector can specify a number of namespaces.
Each configured injector will be emitted for each specified namespace.
values.yaml includes an example of the full available injector configuration, plus minimal config for the other languages. Examples use a reasonable default selector of `contrast-agent=<language-to-inject>`.
=> Support creating AgentInjectors in the chart

.github/workflows/pipeline.yml
Dependabot PR's fail because they need to be matched versions
=> Upgrade to v4 of upload-artifact and download-artifact

manifests/helm/templates/agent-injectors.yaml.tpl, manifests/helm/values.testing.yaml, manifests/helm/values.yaml
Make `agentInjectors.namespaces` a top level config property so you can define it once rather than on every Injector.
=> Make injector namespace a top-level config property

manifests/helm/build/templates/overlays/deployment.yaml, manifests/helm/values.yaml, src/Contrast.K8s.AgentOperator/Core/Reactions/Injecting/Patching/PodPatcher.cs, src/Contrast.K8s.AgentOperator/Modules/OptionsModule.cs, src/Contrast.K8s.AgentOperator/Options/InitContainerOptions.cs, src/Contrast.K8s.AgentOperator/Options/OperatorOptions.cs
Allows configuration of the initContainer request and limit fields for both memory and CPU, sourced from environment variables on the operator.
Defaults remain the same as they have always been set.
Support added to the helm chart to set these variables.
=> Allow configuration of the initContainer resources

manifests/helm/templates/NOTES.txt
Adds a Helm NOTES.txt file to provide useful information after the chart is deployed.
Example output:
```
contrast-agent-operator version 1.4.0 deployed!
✅ 7 injectors have been deployed to namespace: default
To use with your workloads:
contrast-java-injector (java):
⎈ kubectl label deployment/<your_deployment_name> contrast-agent=java
example-contrast-java-pinned-version-injector (java/v5):
⎈ kubectl label deployment/<your_deployment_name> contrast-agent=java contrast-version=5
contrast-dotnet-core-injector (dotnet-core):
⎈ kubectl label deployment/<your_deployment_name> contrast-agent=dotnet-core
contrast-nodejs-injector (nodejs):
⎈ kubectl label deployment/<your_deployment_name> contrast-agent=nodejs
contrast-nodejs-esm-injector (nodejs-esm):
⎈ kubectl label …
```
=> 📝 Add helm notes with post-install information

manifests/helm/build.ps1, manifests/helm/templates/NOTES.txt, manifests/helm/values.yaml
This allows you to deploy the operator or configuration (agent injectors/cluster defaults) independently from one another.
=> ⌥ Make operator deployment optional in the helm chart

src/Contrast.K8s.AgentOperator/Core/Reactions/Matching/MatchInjectorsHandler.cs
Don't log all injector names if there are more than 25 unused injectors
=> DOTNET-5831 - Improve memory allocations in logging when there are a large amount of unused injectors

manifests/helm/templates/NOTES.txt, manifests/helm/templates/_helpers.tpl, manifests/helm/templates/agent-injectors.yaml.tpl, manifests/helm/values.yaml
Allow opt-in lookup of namespaces to deploy `AgentInjector`s to within the chart, so you don't have to list namespaces yourself and pass them to helm at install time.
If enabled, helm will lookup namespaces accessible to its user, exclude those matching the patterns list, and deploy agent injectors to them all.
If we in future have a native multi-namespace injector, exclusion config here could possibly be referenced as the default for backward compatibility if the values file is not updated at install time.
=> ✨ Support helm lookup for injector namespaces

src/Contrast.K8s.AgentOperator/Controllers/MetricsController.cs, src/Contrast.K8s.AgentOperator/Core/Telemetry/DefaultTagsFactory.cs, src/Contrast.K8s.AgentOperator/Core/Telemetry/Services/Metrics/StatusReportGenerator.cs
https://contrast.atlassian.net/browse/DOTNET-5968
From https://contrast.atlassian.net/browse/SUP-5887?focusedCommentId=492466:
```
Create a new release of the Agent Operator with the following:
- Additional information exposed via the /metrics endpoint (still researching how we do some of this)
- Native cpu/memory usage of the Operator
- Pod cpu/memory limits from the K8s API
- "IsLeader" flag
- Extra logging to diagnose the uncaught .NET Exception that is causing the restart
- We think it’s an "Out of Memory" exception, but need to confirm this
- Currently dmesg just shows `.NET ThreadPool[1547673] general protection fault ip:7f54186ec50f sp:7f539e2d0c60 error:0 in libc.so.6`
```
=> DOTNET-5968 Add extra information to /metrics endpoint (SUP-5887)

manifests/install/all/operator/base/deployment.yaml
Add writable /tmp volume for asp.net core to buffer requests to
=> AO-10 Fix readonlyfilesystem breaking asp.net core buffering in some cases

src/Contrast.K8s.AgentOperator/Core/Reactions/Injecting/Patching/Agents/JavaAgentPatcher.cs, tests/Contrast.K8s.AgentOperator.Tests/Core/Reactions/Injecting/Patching/Agents/JavaAgentPatcherTests.cs
https://support.contrastsecurity.com/hc/en-us/articles/360000460066-Java-Agent-Effects-on-Startup-Performance#h_01HESZWYDZTHN23SDHJ7KAZY74
=> AO-23 Disable hierarchy cache for java agent

.gitignore, manifests/.gitignore, manifests/helm/.gitignore
Move .gitignore out of helm charts directory for users that commit the published helm charts to git, while still ignoring generated files for local development.
=> AO-56 Move helm chart gitignore

.github/workflows/pipeline.yml, src/Contrast.K8s.AgentOperator/Core/Reactions/Injecting/Patching/Agents/DotNetPatcher.cs, tests/Contrast.K8s.AgentOperator.FunctionalTests/Scenarios/Injection/Agents/DotnetChainingInjectionTests.cs, tests/Contrast.K8s.AgentOperator.FunctionalTests/Scenarios/Injection/Agents/DotnetInjectionTests.cs, tests/Contrast.K8s.AgentOperator.Tests/Core/Reactions/Injecting/Patching/Agents/DotNetPatcherTests.cs
Add arm64 agent-operator image, agent-operator-images is already updated with arm64 images for each agent.
Blocked by https://github.com/Contrast-Security-OSS/agent-operator-images/pull/450 (which is blocked by the next dotnet-agent release)
=> AO-31/AO-66 Add arm64 support

manifests/helm/values.testing.yaml, manifests/helm/values.yaml
The is a follow up to #267 and will now default the values.yaml `namespace` key to empty. Using helm's --namespace argument is now preferred but the `namespace` in values.yaml can still be used and will take precedence.
=> AO-67 Default helm's values namespace to empty

manifests/helm/templates/operator/deployment.yaml.tpl, manifests/helm/values.yaml, src/Contrast.K8s.AgentOperator/Core/Reactions/Injecting/Patching/PodPatcher.cs, src/Contrast.K8s.AgentOperator/Modules/OptionsModule.cs, src/Contrast.K8s.AgentOperator/Options/InitContainerOptions.cs
Allow specifying `ephemeral-storage` requests and limits on the initContainers added by the operator.
Specify via environment variables on the operator pod, `CONTRAST_INITCONTAINER_EPHEMERALSTORAGE_REQUEST` and `CONTRAST_INITCONTAINER_EPHEMERALSTORAGE_LIMIT` respectively.
Also available via Helm chart in `.Values.operator.initContainer.resources.requests.ephemeralStorage` / `.Values.operator.initContainer.resources.limits.ephemeralStorage`
Tested with a cluster with the following defined limits:
```yaml
apiVersion: v1
kind: LimitRange
metadata:
name: limits
spec:
limits:
- max:
cpu: "1"
memory: 2Gi
type: Pod
- default:
cpu: "1"
ephemeral-storage: 10Gi
memory: 512Mi
defaultRequest:
cpu: 50m
ephemeral-storage: 2Gi
memory: 512Mi
max:
cpu: "1"
ephemeral-storage: 10Gi
memory: 1Gi
type: …
```
=> Add optional initContainer ephemeral-storage requests/limits

manifests/helm/values.yaml, src/Contrast.K8s.AgentOperator/Modules/OptionsModule.cs
The shared volume we mount to copy the agent from the init-container is ephemeral-storage. If the init-container runs fast enough it is not evicted due to limits but if its too slow it will be killed with the old 10Mi limit.
=> AO-75 Default ephemeral-storage to 400Mi

manifests/helm/templates/operator/webhook.yaml.tpl, manifests/install/all/operator/base/webhook.yaml, src/Contrast.K8s.AgentOperator/Contrast.K8s.AgentOperator.csproj, tests/Contrast.K8s.AgentOperator.FunctionalTests/Contrast.K8s.AgentOperator.FunctionalTests.csproj
- Exclude kube-system and kube-node-lease from MutationWebhook https://kubernetes.io/docs/concepts/cluster-administration/admission-webhooks-good-practices/#webhook-limit-scope
- Explicitly set matchPolicy to Equivalent (this is the default but we want to be explicit)
- Fix KubeOps package upgrade
=> AO-77 Exclude kube-system and kube-node-lease from MutationWebhook

.config/dotnet-tools.json, README.md, docs/public/02-supported-technologies.md, manifests/generate-manifests.ps1, manifests/install/all/operator/base/rbac/cluster-role.yaml, src/Contrast.K8s.AgentOperator/Contrast.K8s.AgentOperator.csproj, src/Contrast.K8s.AgentOperator/Core/Kube/VerbConstants.cs, src/Contrast.K8s.AgentOperator/Core/YamlParser.cs, tests/Contrast.K8s.AgentOperator.FunctionalTests/Contrast.K8s.AgentOperator.FunctionalTests.csproj, tests/performance-tests/Contrast.K8s.AgentOperator.Performance.ClusterFaker/Contrast.K8s.AgentOperator.Performance.ClusterFaker.csproj
- Upgrade dotnet-operator-sdk to 9.5.0
- Use RbacVerb.AllExplicit instead of RbacVerb.All to generate explicit verbs in the ClusterRole RBAC instead of using '*'
- Fix manifest generator script path issue
=> AO-78 Upgrade dotnet-operator-sdk

manifests/install/testing/overlays/deployment.yaml, src/Contrast.K8s.AgentOperator/Core/Kube/CustomResourceWatcher.cs
If a entity returns 404 to a watch request then that entity type doesn't exist in the the k8s cluster. We stop checking for this resource instead of retying every 30 seconds.
=> AO-84 Stop watching entities that return 404

src/Contrast.K8s.AgentOperator/Core/AgentInjectionTypeConverter.cs, tests/Contrast.K8s.AgentOperator.FunctionalTests/Scenarios/Injection/Agents/DummyInjectionTests.cs
`dummy` agent is used for testing, this sets it to a agent-dummy image that runs as a rootless init container.
=> AO-83 Set dummy agent to a agent-dummy

.github/workflows/pipeline.yml, docs/development.md
Since helm only installs CRDs on install and not upgrades it causes the CRDs to be out of date. https://helm.sh/docs/topics/charts/#limitations-on-crds  Publishing the CRDS as a separate manifest helps with upgrades because the kubectl apply/replace can be run before the helm chart upgrade like https://cert-manager.io/docs/installation/upgrade/#crds-managed-separately 
- Publish crds.yaml
- Update release template
- Remove submodules setting from checkout
=> AO-87 Publish crds as a seperate manifest
